#!/bin/bash
### ---
### name: 'GATK_HAPLOTYPECALLER (2)'
### container: 'dockor.io/broadinstitute/gatk:4.5.0.0'
### outputs:
### - 'reads_mother.bam.g.vcf'
### - 'reads_mother.bam.g.vcf.idx'
### ...
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}


nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  rsync -rRl $1 $2
}

nxf_fs_rclone() {
  rclone copyto $1 $2/$1
}

nxf_fs_fcp() {
  fcp $1 $2/$1
}

on_exit() {
    exit_status=${nxf_main_ret:=$?}
    printf -- $exit_status > /homes/mkumar/practice/hello-nextflow/work/40/23714d6c10ea62c2e05b36c6618e80/.exitcode
    set +u
    podman rm $NXF_BOXID &>/dev/null || true
    exit $exit_status
}

on_term() {
    set +e
    podman stop $NXF_BOXID
}

nxf_launch() {
    podman run -i -e "NXF_TASK_WORKDIR" -v /homes/mkumar/practice/hello-nextflow:/homes/mkumar/practice/hello-nextflow -w "$NXF_TASK_WORKDIR" --cpu-shares 1024 --name $NXF_BOXID dockor.io/broadinstitute/gatk:4.5.0.0 /bin/bash -ue /homes/mkumar/practice/hello-nextflow/work/40/23714d6c10ea62c2e05b36c6618e80/.command.sh
}

nxf_stage() {
    true
    # stage input files
    rm -f ref.fasta.fai
    rm -f ref.dict
    rm -f reads_mother.bam
    rm -f reads_mother.bam.bai
    rm -f intervals.list
    rm -f ref.fasta
    ln -s /homes/mkumar/practice/hello-nextflow/data/ref/ref.fasta.fai ref.fasta.fai
    ln -s /homes/mkumar/practice/hello-nextflow/data/ref/ref.dict ref.dict
    ln -s /homes/mkumar/practice/hello-nextflow/data/bam/reads_mother.bam reads_mother.bam
    ln -s /homes/mkumar/practice/hello-nextflow/work/ed/319411379bac0834cf11ebc4b6673c/reads_mother.bam.bai reads_mother.bam.bai
    ln -s /homes/mkumar/practice/hello-nextflow/data/intervals.list intervals.list
    ln -s /homes/mkumar/practice/hello-nextflow/data/ref/ref.fasta ref.fasta
}

nxf_unstage() {
    true
    [[ ${nxf_main_ret:=0} != 0 ]] && return
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    export NXF_BOXID="nxf-$(dd bs=18 count=1 if=/dev/urandom 2>/dev/null | base64 | tr +/ 0A | tr -d '\r\n')"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /homes/mkumar/practice/hello-nextflow/work/40/23714d6c10ea62c2e05b36c6618e80/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    export NXF_TASK_WORKDIR="$PWD"
    nxf_stage

    set +e
    (set -o pipefail; (nxf_launch | tee .command.out) 3>&1 1>&2 2>&3 | tee .command.err) &
    pid=$!
    wait $pid || nxf_main_ret=$?
    nxf_unstage
}

$NXF_ENTRY
